@startuml
!include <awslib/AWSCommon.puml>
!include <awslib/AWSSimplified.puml>
!include <awslib/Compute/all.puml>
!include <awslib/Database/DynamoDB.puml>
!include <awslib/general/users.puml>
!include <awslib/mobile/apigateway.puml>

left to right direction

Users(jira, "Jira users", "millions of users")
Users(confluence, "Confluence users", "millions of users")
APIGateway(renderingAPI, "Rendering API", "declarative charts/diagrams")
ElasticContainerService(renderECSVisualization, "Docker engines", "return jwt")
Lambda(renderLambdaVisualization, "Lambda engines", "return jwt")
DynamoDB(atlassian, "Atlassian Cloud", "one entry per user")

jira--> renderingAPI
confluence--> renderingAPI
renderingAPI --> renderECSVisualization
renderingAPI --> renderLambdaVisualization
renderECSVisualization--> atlassian
renderLambdaVisualization--> atlassian
@enduml
